/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721A from "./ERC721a";
export type { erc721A };
export type { ArchetypeBatch } from "./ArchetypeBatch";
export type { ArchetypePayouts } from "./ArchetypePayouts";
